
/**************************************************************
 *	
 *	bark, 8 bit, 11025Hz,
 *	1 channel, 24765 bytes/channel
 *	Total Size: 1 * 24765 + 4 (header) = 24809 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/lianfeng/Desktop/bark.wav
 *	Time-stamp: Tue Nov 28 19:59:32 2017
 *	
 **************************************************************/

#ifndef __BARKH__
#define __BARKH__

#define BARKFREQ 11025
#define BARKLEN 24765

extern const unsigned char bark[24765];

#endif /* __BARKH__ */
