
/**************************************************************
 *	
 *	gamemusic, 8 bit, 11025Hz,
 *	1 channel, 1155168 bytes/channel
 *	Total Size: 1 * 1155168 + 4 (header) = 1155212 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/lianfeng/Desktop/gamemusic.wav
 *	Time-stamp: Tue Nov 28 17:06:58 2017
 *	
 **************************************************************/

#ifndef __GAMEMUSICH__
#define __GAMEMUSICH__

#define GAMEMUSICFREQ 11025
#define GAMEMUSICLEN 115516


extern const unsigned char gamemusic[1155168];


#endif /* __GAMEMUSICH__ */
