
/**************************************************************
 *	
 *	rustle, 8 bit, 11025Hz,
 *	1 channel, 4896 bytes/channel
 *	Total Size: 1 * 4896 + 4 (header) = 4940 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/lianfeng/Desktop/rustle.wav
 *	Time-stamp: Tue Nov 28 17:47:09 2017
 *	
 **************************************************************/

#ifndef __RUSTLEH__
#define __RUSTLEH__

#define RUSTLEFREQ 11025
#define RUSTLELEN 4896

extern const unsigned char rustle[4896];

#endif /* __RUSTLEH__ */
