
/**************************************************************
 *	
 *	startsound, 8 bit, 11025Hz,
 *	1 channel, 1166688 bytes/channel
 *	Total Size: 1 * 1166688 + 4 (header) = 1166732 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/lianfeng/Desktop/startsound.wav
 *	Time-stamp: Tue Nov 28 18:57:32 2017
 *	
 **************************************************************/

#ifndef __STARTSOUNDH__
#define __STARTSOUNDH__

#define STARTSOUNDFREQ 11025
#define STARTSOUNDLEN 1166688

extern const unsigned char startsound[1166688];

#endif /* __STARTSOUNDH__ */
